SET DATABASE REFERENTIAL INTEGRITY FALSE

INSERT INTO PUBLIC.ACTS (ID) values (1);
INSERT INTO PUBLIC.ACTS (ID) values (2);
INSERT INTO PUBLIC.ACTS (ID) values (3);
INSERT INTO PUBLIC.ACTS (ID) values (4);
INSERT INTO PUBLIC.ACTS (ID) values (5);

INSERT INTO PUBLIC.BANDS (ACTID, NAME) values (1, 'Led Zeppelin');
INSERT INTO PUBLIC.BANDS (ACTID, NAME) values (2, 'U2');

INSERT INTO PUBLIC.ARTISTS (ACTID, FIRSTNAME, LASTNAME) values (3, 'Robert', 'Plant');
INSERT INTO PUBLIC.ARTISTS (ACTID, FIRSTNAME, LASTNAME) values (4, 'Jimmy', 'Page');
INSERT INTO PUBLIC.ARTISTS (ACTID, FIRSTNAME, LASTNAME) values (5, 'John', 'Bonham');

INSERT INTO PUBLIC.ALBUMS(ID, NAME, YEAR) values (1, 'Led Zeppelin', 1969);
INSERT INTO PUBLIC.ALBUMS(ID, NAME, YEAR) values (2, 'Led Zeppelin II', 1970);
INSERT INTO PUBLIC.ALBUMS(ID, NAME, YEAR) values (3, 'Led Zeppelin III', 1971);
INSERT INTO PUBLIC.ALBUMS(ID, NAME, YEAR) values (4, 'Led Zeppelin IV', 1972);
INSERT INTO PUBLIC.ALBUMS(ID, NAME, YEAR) values (5, 'Houses of the Holy', 1973);

INSERT INTO PUBLIC.ALBUM_ACTS (ACTID, ALBUMID) values (1, 1);
INSERT INTO PUBLIC.ALBUM_ACTS (ACTID, ALBUMID) values (1, 2);
INSERT INTO PUBLIC.ALBUM_ACTS (ACTID, ALBUMID) values (1, 3);
INSERT INTO PUBLIC.ALBUM_ACTS (ACTID, ALBUMID) values (1, 4);
INSERT INTO PUBLIC.ALBUM_ACTS (ACTID, ALBUMID) values (1, 5);

SET DATABASE REFERENTIAL INTEGRITY TRUE

